export const phoneNumber: string = "+36 30 813 3821";
export const phoneNumberLink: string = `tel:${phoneNumber.replace(" ", "")}`;
export const siteUrl: string = "https://hollo-vill.hu";
export const email: string = "info@hollo-vill.hu";
export const emailLink: string = `mailto:${email}`;
export const companyName: string = "Holló-Vill";
export const companyOwner: string = "Holló János e.v.";
export const siteLink: string = "https://hollo-vill.hu";
export const facebook: string = "Holló-Vill Villanyszerelés";
export const facebookLink: string =
  "https://www.facebook.com/profile.php?id=61581999308967";
export const address: string = "2851 Környe, November utca 20.";
